### ISSUE TITLE
kernel panic 6/10 times

### ISSUE THREAD

**Issue by sonvirgo** [blankmac/VoodooI2CUPDDEngine#1]
I  got kernel panic very frequent, about 6/10 time?
I have FTSC1000 Which works quite good with VoodooI2c- UPDD-client

**Comment by blankmac** [comment]
As previously mentioned in the gitter chat, have you tried disabling the I2C sensor hub?

**Comment by sonvirgo** [comment]
Something conflict in my system

**Comment by blankmac** [comment]
closed for inactivity.
